<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_MegaMenu
 * @author     Extension Team
 * @copyright  Copyright (c) 2016-2017 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */
 ?>
<?php
$storeId = $this->getRequest()->getParam('store');
if ($storeId == null) {
    $storeId = '0';
}
?>

<div id="m2-component" data-bind="scope:'m2kocomponent'">
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
    {
        "#m2-component": {
            "Magento_Ui/js/core/app": {
               "components": {
                    "m2kocomponent": {
                        "component": "Bss_Megamenu/js/content",
                        "template" : "Bss_Megamenu/content",
                        "storeId": "<?php echo $storeId ?>",
                        "staticBlocks": <?php echo $block->getBlockCollection(); ?>,
                        "categoriesLink": <?php echo $block->getCategoryCollection(); ?>
                    }
                }
            }
        }
    }
    </script>
</div>
