<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_MegaMenu
 * @author     Extension Team
 * @copyright  Copyright (c) 2016-2017 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */
?>
<div class="page-actions-placeholder"></div>
<div data-ui-id="page-actions-toolbar-content-header" class="page-actions">
    <div class="page-actions-inner" data-title="Catalog">
        <div class="page-actions-buttons">

            <div class="actions-split" title="Add Product" id="add_new_product">
                <button data-ui-id="products-list-add-new-product-button" class="primary add" title="Add Product" id="save-menu-button" >
                    <span>Save Menu</span>
                </button>
            </div>

        </div>
    </div>
</div>