<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_MegaMenu
 * @author     Extension Team
 * @copyright  Copyright (c) 2016-2017 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */
?>

<div class="col-md-3">
    <button id="megamenu_add" class="action-default scalable add" type="button" style="margin-bottom:20px">Create</button>
    <div id="megamenu_tree"></div>
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "Bss_Megamenu/js/tree": {
                "urlSave": "<?php echo $block->getNodeUrl('save'); ?>",
                "menuItemUrlLoad": "<?php echo $block->getMenuItemUrl('load'); ?>",
                "menuItemUrlSave": "<?php echo $block->getMenuItemUrl('save'); ?>",
                "menuTree": <?php echo $block->menuTree(); ?>,
                "getNodeUrlDelete": "<?php echo $block->getNodeUrl('delete'); ?>",
                "currentStoreId": "<?php echo $this->getRequest()->getParam('store'); ?>",
                "messageCache": "<?php echo $block->getText(); ?>"
            }
        }
    }
</script>